/*
 * File: app/view/mainView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mainView', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'TaskMaster',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        text: 'Add'
                    }
                ]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'card'
                },
                title: 'Curent',
                iconCls: 'organize',
                items: [
                    {
                        xtype: 'list',
                        id: 'CurrentList',
                        itemId: 'mylist',
                        itemTpl: [
                            '<div class=priority_{priority}>{name}</div>'
                        ],
                        store: 'TaskStore'
                    },
                    {
                        xtype: 'panel',
                        id: 'CurrentDetails',
                        tpl: [
                            '<div class="taskName">{name}</div>',
                            '<div class="taskDescription">{description}</div>',
                            '<div class="taskCreated">Created: {created}</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'card'
                },
                title: 'Completed',
                iconCls: 'delete',
                items: [
                    {
                        xtype: 'list',
                        id: 'CompletedList',
                        itemTpl: [
                            '<div class=priority_{priority}>{name}</div>'
                        ],
                        store: 'CompletedStore'
                    },
                    {
                        xtype: 'panel',
                        id: 'CompletedDetails',
                        tpl: [
                            '<div class="taskName">{name}</div>',
                            '<div class="taskDescription">{description}</div>',
                            '<div class="taskCreated">Created: {created}</div>',
                            '<div class="taskCompleted">Completed: {completed}</div>'
                        ]
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        },
        listeners: [
            {
                fn: 'onCurrentListSelect',
                event: 'select',
                delegate: '#CurrentList'
            }
        ]
    },

    onCurrentListSelect: function(dataview, record, options) {
        var currentTab = this.up('container');
        console.log(currentTab);

        var currentDetails = currentTab.down('panel');
        console.log(currentDetails);

        currentDetails.setRecord(record);
        currentTab.setActiveItem(currentDetails);
    }

});