/*
 * File: app/view/mainView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mainView', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'TaskMaster',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        text: 'Add'
                    }
                ]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'card'
                },
                title: 'Curent',
                iconCls: 'organize',
                items: [
                    {
                        xtype: 'list',
                        id: 'CurrentList',
                        itemTpl: [
                            '<div class=priority_{priority}>{name}</div>'
                        ]
                    },
                    {
                        xtype: 'panel',
                        id: 'CurrentDetails',
                        tpl: [
                            '<div class="taskName">{name}</div>',
                            '<div class="taskDescription">{description}</div>',
                            '<div class="taskCreated">Created: {created}</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'card'
                },
                title: 'Completed',
                iconCls: 'delete',
                items: [
                    {
                        xtype: 'list',
                        id: 'CompletedList',
                        itemTpl: [
                            '<div class=priority_{priority}>{name}</div>'
                        ]
                    },
                    {
                        xtype: 'panel',
                        id: 'CompletedDetails'
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});